name: Build Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build documentation
      run: npm run build

    - name: Test build output
      run: |
        if [ ! -d "build" ]; then
          echo "Build directory not found!"
          exit 1
        fi
        if [ ! -f "build/index.html" ]; then
          echo "Index.html not found in build!"
          exit 1
        fi
        echo "Build successful!"

    - name: Upload build artifacts
      if: matrix.node-version == '20.x' && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: documentation-build
        path: build/
        retention-days: 7

  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for TypeScript errors
      run: npx tsc --noEmit

    - name: Check documentation links
      run: |
        echo "Checking for broken internal links..."
        npm run build 2>&1 | tee build.log
        if grep -q "Broken link" build.log; then
          echo "❌ Broken links found!"
          grep "Broken link" build.log
          exit 1
        else
          echo "✅ No broken links found!"
        fi 